### ISSUE TITLE
loading indicator, nicer arks

### ISSUE THREAD

**Issue by loicjaouen** [gustaveroudproject/roud-oeuvres-app#162]

**Comment by elespdn** [comment]
Start working on the loader (for now, implemented only ms-page) on branch https://github.com/gustaveroudproject/roud-oeuvres-app/tree/wip/%23162

The mechanism to show it is the same as in https://github.com/dasch-swiss/dsp-app/blob/d16e5b5032268dc99c6f46e55de10ed10127c530/src/app/workspace/resource/values/link-value/link-value.component.ts (`loadingResults = true`).

The problem is that it should last more. Now it is active until the answer to retrieve the pages (images) arrive, which is the last response looking at the logs ... but it is not enough.

**Comment by loicjaouen** [comment]
please have a look, I propose to increment the tag at each expected result and to systematically decrease it whenever the request ends.

Do you have a link to get into a MsPage?

**Comment by elespdn** [comment]
I will have a look, thanks!
Here it is a link to a ms: https://github.com/gustaveroudproject/roud-oeuvres-app/issues/162#issuecomment-1256201512

**Comment by loicjaouen** [comment]
it works better on the full-text search, I'll have a look at MsPage

**Comment by elespdn** [comment]
On the following components:

- [ ] essay-page
- [ ] essays-page
- [ ] ms-page
- [ ] person-page
- [ ] place-page
- [ ] pub-page
- [ ] search-page
- [ ] text-page
- [ ] work-page
